[package]
name = "freesync-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "freesync"
path = "src/main.rs"

[dependencies]
freesync-core = { path = "../core" }
freesync-google = { path = "../google" }
clap.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true

